#
# espmotors.yaml
# ESPmotors revB configuration file for ESPHome, see https://esphome.io
# https://Climbers.net (c) 2022
#
esphome:
  name: ESPmotors
  platform: ESP8266
  board: esp12e

mcp23017:
  - id: mcp
    address: 0x20

#
# Stepper motor #1, with associated limit switch and 3 microstepping control pins
#
stepper:
  - platform: a4988
    id: motor1
    step_pin: GPIO14
    dir_pin: 
      mcp23xxx: mcp
      number: 0
    max_speed: 5000 steps/s
    sleep_pin:
      mcp23xxx: mcp
      number: 1

# limit switch #1 pressed
binary_sensor:
  - platform: gpio
    name: limit1
    pin:
      mcp23xxx: mcp
      number: 7
    filters:
      - invert:
      
# ms1 | ms2 | ms3 | stepping mode
# ----+-----+-----+--------------------
# OFF | OFF | OFF | full step (default)
# ON  | OFF | OFF | 1/2 step
# OFF | ON  | OFF | 1/4 step
# ON  | ON  | OFF | 1/8 step
# ON  | ON  | ON  | 1/16 step
switch:
  - platform: gpio
    pin: 
      mcp23xxx: mcp
      number: 2
    name: speed1_ms3
  - platform: gpio
    pin: 
      mcp23xxx: mcp
      number: 3
    name: speed1_ms2
  - platform: gpio
    pin: 
      mcp23xxx: mcp
      number: 4
    name: speed1_ms1
    
#
# Stepper motor #2, with associated limit switch and 3 microstepping control pins
#
stepper:
  - platform: a4988
    id: motor2
    step_pin: GPIO12
    dir_pin:
      mcp23xxx: mcp
      number: 8
    max_speed: 5000 steps/s
    sleep_pin:
      mcp23xxx: mcp
      number: 9

# limit switch #2 pressed
binary_sensor:
  - platform: gpio
    name: limit2
    pin:
      mcp23xxx: mcp
      number: 15
    filters:
      - invert:

switch:
  - platform: gpio
    pin: 
      mcp23xxx: mcp
      number: 10
    name: speed2_ms3
  - platform: gpio
    pin: 
      mcp23xxx: mcp
      number: 11
    name: speed2_ms2
  - platform: gpio
    pin: 
      mcp23xxx: mcp
      number: 12
    name: speed2_ms1
